### ISSUE TITLE
Merging this project and mine?

### ISSUE THREAD

**Issue by fge** [JeffreyFalgout/ThrowingStream#1]
I have discovered this project some time ago but worked on some sort of an alternative: [throwing-lambdas](https://github.com/fge/throwing-lambdas).

To me, it appears that both project try and work around the fact that you cannot throw checked exceptions from `Stream`s, except that the approach of your project is different and, I think, ultimately better, than mine.

Would you be interested in taking over throwing-lambdas and incorporate the parts of it which you find interesting into ThrowingStream?

**Comment by JeffreyFalgout** [comment]
I wouldn't be against it. Unfortunately, I am going to be fairly busy for the foreseeable future and I'm not sure when I'll be able to get around to it.

**Comment by JeffreyFalgout** [comment]
Well, it's kind of funny, but I started getting interested in this project again so I should be able to make the time to work on it. I like your idea of `fallbackTo` and `orTryWith` and I'll work on implementing those as default methods in my Throwing interfaces.

**Comment by fge** [comment]
Note that the PREVIOUS version of throwing-lambdas (0.3.0) did rely on interfaces for that; however that turned out to be "interface abuse" in some ways which is why I rely on classes in 0.4.0.

Now, to be fair, I have had only a cursory look at your code so far, but I believe your basic approach has more merits than mine. Also, just in case, I have added "sneaky throw" support as well recently (not released).

I'd love to be able to discuss it further!

**Comment by JeffreyFalgout** [comment]
Why do you think it's interface abuse? I don't really think it's too much worse than [`Function`](https://docs.oracle.com/javase/8/docs/api/java/util/function/Function.html)'s default methods.

I went ahead and implemented them as default methods, but I suppose I can always go back and extract them to a separate class. Take a look at the [`throwing-lambda` branch](https://github.com/JeffreyFalgout/ThrowingStream/tree/throwing-lambda). In order to save some amount of repetition, the only actual implementation is in [`ThrowingSupplier`](https://github.com/JeffreyFalgout/ThrowingStream/blob/throwing-lambda/src/main/java/throwing/function/ThrowingSupplier.java). Every other interface uses `ThrowingSupplier`'s `fallbackTo` and `orTry` methods.

The main difference I see right now with my implementation is that if *any* exception is thrown from the first interface, not just `X`, the `fallback` will be invoked. [Your implementation](https://github.com/fge/throwing-lambdas/blob/0.3.0/src/main/java/com/github/fge/lambdas/suppliers/ThrowingSupplier.java#L55) only caught checked exceptions and allowed other `Error`s and `RuntimeException`s to trickle through.

I will be on vacation for the next week.

**Comment by JeffreyFalgout** [comment]
I went ahead and merged that branch into master.
